# Generated by Django 5.0 on 2024-01-04 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='tittle',
            new_name='title',
        ),
    ]
